run_04:
	@g++ -std=c++17 ./04.ConcertTickets.cpp -o a.out && ./a.out < testcase
run_05:
	@g++ -std=c++17 ./05.RestaurantCustomers.cpp -o a.out && ./a.out < testcase
run_06:
	@g++ -std=c++17 ./06.MovieFestival.cpp-o a.out && ./a.out < testcase
run_07:
	@g++ -std=c++17 ./07.SumOfTwoValues.cpp -o a.out && ./a.out < testcase
run_08:
	@g++ -std=c++17 ./08.MaximumSubarraySum.cpp -o a.out && ./a.out < testcase
